class TOUCHSENSOR_CONFIG:
    MAX_VALUE = 2048


class LOSS_WEIGHT_CONFIG:
    RECTANGLE_SIZE = 2
    ALPHA_FACTOR = 20


class TRAINING_CONFIG:
    GP_WEIGHT = 10
    CRITIC_ITER = 5
    INITIAL_LR = 0.0005
    MINIMUM_LR = 5e-5
    DEFAULT_EPOCH = 50
    PATIENT_EPOCH = 5
    N_VAL_SNAPSHOTS = 5
    THRESHOLD = 0.9


class INFERENCE_CONFIG:
    THRESHOLD = 0.7


class SUPERRES_CONFIG:
    FACTOR = 8
